plugins {
  id 'java'
  id 'org.springframework.boot' version '3.5.7'
  id 'io.spring.dependency-management' version '1.1.7'
  id 'com.diffplug.spotless' version "7.0.4"
  id 'org.owasp.dependencycheck' version "12.1.8"
  id 'org.cyclonedx.bom' version '2.3.1'
}

apply from: 'corporate/release.gradle'
apply from: 'corporate/security.gradle'
apply from: 'corporate/spotless.gradle'

group = 'de.miq'
version = '0.0.1-SNAPSHOT'
description = 'Digital Radio Manager'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-web'
  developmentOnly 'org.springframework.boot:spring-boot-devtools'
  runtimeOnly 'org.postgresql:postgresql'
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
  useJUnitPlatform()
}
